# Everforest (Dark Medium)
# Authors: CptPotato, basbebe

# Original Author:
# URL: https://github.com/sainnhe/everforest
# Filename: colors/everforest.vim
# Author: sainnhe
# Email: sainnhe@gmail.com
# License: MIT License

"type" = {fg ="yellow", modifiers = ["italic"]}
"constant" = "fg"
"constant.builtin" = { fg = "purple", modifiers = ["italic"] }
"constant.builtin.boolean" = "purple"
"constant.numeric" = "purple"
"constant.character.escape" = "green"
"string" = { fg = "green"}
"string.regexp" = "green"
"string.special" = "yellow"
"comment" = { fg = "grey1", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = { fg = "purple", modifiers = ["italic"] }
"variable.parameter" = "fg"
"variable.other.member" = "blue"
"label" = "orange"
"punctuation" = "grey2"
"punctuation.delimiter" = "grey1"
"punctuation.bracket" = "orange" 
"punctuation.special" = "blue"
"keyword" = "red"
"keyword.operator" = "orange"
"keyword.directive" = "purple"
"keyword.storage" = "red"
"operator" = "orange"
"function" = "green"
"function.macro" = "green"
"tag" = "orange"
"namespace" = { fg = "yellow", modifiers = ["italic"] }
"attribute" = { fg = "purple", modifiers = ["italic"] }
"constructor" = "green"
"module" = "yellow"
"special" = "blue"

"markup.heading.marker" = "grey1"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "purple", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", underline = { style = "line" } }
"markup.link.label" = "orange"
"markup.link.text" = "purple"
"markup.quote" = "grey1"
"markup.raw.inline" = "green"
"markup.raw.block" = "aqua"

"diff.plus" = "green"
"diff.delta" = "blue"
"diff.minus" = "red"

# "ui.background" = { fg = "foreground" }
"ui.background" = { bg = "bg0" }

"ui.background.separator" = "bg0"
"ui.statusline.separator" = { fg = "fg", bg = "bg3" }
"ui.cursor" = { fg = "bg1", bg = "grey1" }
"ui.cursor.insert" = { fg = "bg0", bg = "grey1" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.cursor.match" = { fg = "orange", bg = "bg_yellow" }
"ui.cursor.primary" = { fg = "bg0", bg = "fg" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg2" }
"ui.selection" = { bg = "bg3" }
"ui.linenr" = "bg5"
"ui.linenr.selected" = "grey4"
"ui.statusline" = { fg = "grey2", bg = "bg1", modifiers = [ "bold",] }
"ui.statusline.inactive" = { fg = "grey0", bg = "bg2" }
"ui.statusline.normal" = { fg = "bg0", bg = "statusline1", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "bg0", bg = "statusline2", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "bg0", bg = "blue", modifiers = ["bold"] }
"ui.bufferline" = { fg = "grey2", bg = "bg3" }
"ui.bufferline.active" = { fg = "bg0", bg = "statusline1", modifiers = [
  "bold",
] }

### HELP WINDOW
"ui.popup" = { fg = "grey2", bg = "bg1" }
"ui.window" = { fg = "bg4", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg0" }
"ui.text" = "fg"
"ui.text.focus" = "fg"
"ui.menu" = { fg = "fg", bg = "bg2" }
"ui.menu.selected" = { fg = "bg0", bg = "green", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "yellow", bg = "bg1" }
"ui.virtual.ruler" = { bg = "bg3" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4", modifiers = ["bold"] }
"ui.virtual.inlay-hint" = { fg = "grey0" }
"ui.virtual.wrap" = { fg = "grey0" }

"hint" = { fg = "green", modifiers = ["bold"] }
"info" = { fg ="blue", modifiers = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }

"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]

bg_dim = "#1e232600"
bg0 = "#1e2326"
bg1 = "#272e33"
bg2 = "#2e383c"
bg3 = "#374145"
bg4 = "#414b50"
bg5 = "#495156"
bg_visual = "#543a48"
bg_red = "#514045"
bg_green = "#425047"
bg_blue = "#3a515d"
bg_yellow = "#4d4c43"

fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"

grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"

statusline1 = "#a7c080"
statusline2 = "#dbbc7f"
statusline3 = "#e67e80"
